project:
  type: website
  output-dir: docs

website:
  title: "Chart.js: A comprehensive guide to Data Visualisation"
  #navbar:
    #right:
      - #href: index.qmd
        #text: Home
      - #href: blog.qmd
        #text: Blog


format:
  html:
    theme:
      dark: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto