project:
  type: website
  output-dir: docs

website:
  title: "PSDV Exposition Website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Chartjs_blog.ipynb
        text: Blog


format:
  html:
    theme:
      dark: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto